### ISSUE TITLE
добавить в runtest чистильщик папки build

### ISSUE THREAD

**Issue by votol** [DAlexis/finite-phase-volumes-particle-system-modeller#16]
В общем чтобы прога не выдавала ошибку при задании другого конфига. Правда если переделать компиляцию под cmake и добавить кодогенерацию CMakeLists то проболема сама решится

**Comment by DAlexis** [comment]
Под CMake - переделать стоит в перспективе. Пока я подправил скрипт runtest и добавил очистку папки test, в которой генерится код по конфигу. Ну и папки build целиком. Но это спорное решение: так можно потерять результаты счёта.
